"""
AGENT: Landing Page Generator
Input: campaign brief (offer, audience, CTA).
Output: complete HTML landing page file + Zoho Campaigns signup form embed.

The page is generated by Claude, written to disk, and pushed to GitHub Pages
automatically. Zero design decisions required from you.

Usage:
  python agent_landing_page.py \
    --offer "Maldives Private Villa — June 2026" \
    --audience "HNI couples, anniversary / honeymoon" \
    --cta "Book a 20-minute discovery call" \
    --slug "maldives-june"

Output: /Users/openclaw/veltm-butler-button/campaigns/{slug}/index.html
Auto-pushed to: https://lobodotstreehouse.github.io/veltm-butler-button/campaigns/{slug}/
"""

import argparse
import anthropic
import subprocess
import os
from pathlib import Path
from zoho_client import zoho, cliq_post
import requests

REPO_PATH = "/Users/openclaw/veltm-butler-button"
CLIQ_CHANNEL = "marketing"
CAL_LINK = os.environ.get("CALENDLY_LINK", "https://www.butlerbutton.co")


def run(offer: str, audience: str, cta: str, slug: str) -> dict:
    client = anthropic.Anthropic()

    prompt = f"""You are building a high-converting landing page for Butler Button — a premium luxury travel concierge.

Offer: {offer}
Target audience: {audience}
CTA: {cta}

Generate a complete, self-contained HTML page. Requirements:
1. Dark, premium aesthetic: background #0a0a0a, accent gold #C9A84C, white text
2. Mobile-first, single column
3. Structure:
   - Hero: bold headline (10 words max, benefit-led) + one subhead sentence
   - One credibility line (no client names — use "our clients" language)
   - 3 specifics about this offer (not generic benefits — specific to {offer})
   - Social proof block: one testimonial quote (invent a plausible one, first name + city only)
   - CTA section: button linking to {{{{CTA_LINK}}}} placeholder
4. No navigation, no footer links, no distractions
5. Inline all CSS in a <style> block
6. Include a simple HTML form with: First Name, Email, Phone, "Tell us about your trip" textarea
   Form action="#" method="post" id="inquiry-form"
7. Font: system-ui stack — no Google Fonts CDN

Output ONLY the complete HTML. No markdown, no explanation."""

    resp = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=4000,
        messages=[{"role": "user", "content": prompt}]
    )
    html = resp.content[0].text.strip()
    html = html.replace("{{CTA_LINK}}", CAL_LINK)

    # Write to repo
    out_dir = Path(REPO_PATH) / "campaigns" / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "index.html"
    out_file.write_text(html, encoding="utf-8")

    # Git commit + push
    subprocess.run(["git", "-C", REPO_PATH, "add", f"campaigns/{slug}/"], check=True)
    subprocess.run(["git", "-C", REPO_PATH, "commit", "-m",
                    f"Add landing page: {slug}\n\nCo-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"],
                   check=True)
    subprocess.run(["git", "-C", REPO_PATH, "push", "origin", "main"], check=True)

    live_url = f"https://lobodotstreehouse.github.io/veltm-butler-button/campaigns/{slug}/"

    # Cliq
    cliq_post({CLIQ_CHANNEL}, msg)

    return {"slug": slug, "file": str(out_file), "url": live_url}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--offer", required=True)
    parser.add_argument("--audience", required=True)
    parser.add_argument("--cta", required=True)
    parser.add_argument("--slug", required=True)
    args = parser.parse_args()
    result = run(args.offer, args.audience, args.cta, args.slug)
    print(f"\nLive: {result['url']}")
    print(f"File: {result['file']}")
